In [1]:
import joblib
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

import warnings
warnings.filterwarnings("ignore")

In [2]:
X_train = joblib.load("../models/X_train.pkl")
X_test = joblib.load("../models/X_test.pkl")

y_train = joblib.load("../models/y_train.pkl")
y_test = joblib.load("../models/y_test.pkl")

In [3]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": MultinomialNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ),
    "Support Vector Machine": LinearSVC(random_state=42),
    "Neural Network": MLPClassifier(
        hidden_layer_sizes=(100,),
        max_iter=300,
        random_state=42
    )
}

In [4]:
results = []

trained_models = {}

for name, model in models.items():

    print(f"\nTraining {name}...")

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1
    ])

    trained_models[name] = model

Training Logistic Regression...

Training Naive Bayes...

Training Decision Tree...

Training Random Forest...

Training Support Vector Machine...

Training Neural Network...

In [5]:
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

results_df = results_df.sort_values(
    by="Accuracy",
    ascending=False
)

results_df.reset_index(drop=True, inplace=True)

results_df

                    Model  Accuracy  Precision    Recall  F1 Score
0          Neural Network  0.990319   0.991870  0.931298  0.960630
1           Random Forest  0.988383   0.991736  0.916031  0.952381
2     Logistic Regression  0.979671   0.950820  0.885496  0.916996
3  Support Vector Machine  0.977735   0.921875  0.900763  0.911197
4           Decision Tree  0.968054   0.840278  0.923664  0.880000
5             Naive Bayes  0.949661   0.751592  0.900763  0.819444

In [6]:
results_df.style.format({
    "Accuracy": "{:.4f}",
    "Precision": "{:.4f}",
    "Recall": "{:.4f}",
    "F1 Score": "{:.4f}"
})

In [7]:
best_model_name = results_df.iloc[0]["Model"]

print("Best Model:", best_model_name)

Best Model: Neural Network

In [8]:
best_model = trained_models[best_model_name]

joblib.dump(
    best_model,
    "../models/phishing_detector.pkl"
)

print("Best model saved successfully.")

Best model saved successfully.

In [9]:
results_df.to_csv(
    "../reports/model_comparison.csv",
    index=False
)

In [10]:
print("=" * 50)
print("Model Training Completed")
print("=" * 50)

print(results_df)

==================================================
Model Training Completed
==================================================
                    Model  Accuracy  Precision    Recall  F1 Score
0          Neural Network  0.990319   0.991870  0.931298  0.960630
1           Random Forest  0.988383   0.991736  0.916031  0.952381
2     Logistic Regression  0.979671   0.950820  0.885496  0.916996
3  Support Vector Machine  0.977735   0.921875  0.900763  0.911197
4           Decision Tree  0.968054   0.840278  0.923664  0.880000
5             Naive Bayes  0.949661   0.751592  0.900763  0.819444

In [11]:
results_display = results_df.copy()

for col in ["Accuracy", "Precision", "Recall", "F1 Score"]:
    results_display[col] = (results_display[col] * 100).round(2)

results_display

                    Model  Accuracy  Precision  Recall  F1 Score
0          Neural Network     99.03      99.19   93.13     96.06
1           Random Forest     98.84      99.17   91.60     95.24
2     Logistic Regression     97.97      95.08   88.55     91.70
3  Support Vector Machine     97.77      92.19   90.08     91.12
4           Decision Tree     96.81      84.03   92.37     88.00
5             Naive Bayes     94.97      75.16   90.08     81.94